(function(root){
 'use strict';
 const messages={ko:'현재 검증된 데이터가 없어 이 조건은 계산할 수 없습니다. 미검증 값을 0으로 대체하지 않습니다.',en:'This selection cannot be calculated because verified data is unavailable. Unverified values are not replaced with zero.',ja:'検証済みデータがないため、この条件は計算できません。未検証の値を0で代用しません。','zh-tw':'此條件缺少已驗證資料，暫時無法計算。不會以0代替未驗證數值。'};
 function message(){return messages[root.KD_HUB?.lang?.()||'ko']||messages.en;}
 function field(file,path,value){const p=root.KD_PROVENANCE?.[file+'|'+path];return !!(p&&p.status==='VERIFIED'&&p.source&&p.verified_at&&typeof value==='number'&&Number.isFinite(value)&&value>=0&&p.value===value);}
 function steps(kind,data){const file='data/governor-'+kind+'.json',keys=kind==='gear'?['satin','thread','sketch']:['manual','blueprint','attr'];return !!data?.steps&&JSON.stringify(Object.keys(data.steps))===JSON.stringify(root.KD_PROOF_LAYOUT?.[kind])&&Object.keys(data.steps).length>0&&Object.entries(data.steps).every(([stage,row])=>keys.every(k=>field(file,'steps.'+stage+'.'+k,row[k])));}
 const species={graywolf:'common',lynx:'Uncommon',cheetah:'R',lion:'SR','giant-rhino':'SSR'};
 function pet(data,id,rows,from,to){const p=data?.pets?.find(p=>p.id===id),rarity=species[id];if(!p||!rarity||p.rarity!==rarity||!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<=from||to>=rows.length)return false;const raw=data.levelsByRarity[rarity];return rows.slice(from+1,to+1).every(r=>{const i=raw.indexOf(r);return i>=0&&JSON.stringify([r.level,r.type])===JSON.stringify(root.KD_PROOF_LAYOUT?.pets?.[rarity]?.[i])&&['food','notebook','supplement','medal'].every(k=>field('data/pet-upgrade.json','levelsByRarity.'+rarity+'.'+i+'.'+k,r[k]));});}
 function block(host){root.KD_CALCULATOR_RESULT=null;const inventory=root.document?.getElementById('calc-inventory');if(inventory)inventory.replaceChildren();for(const id of ['gc-thr','gc-sat','gc-sk','gc-score','cc-manual','cc-design','cc-attr-total','cc-inf-attr','cc-cav-attr','cc-arc-attr']){const e=root.document?.getElementById(id);if(e)e.textContent='—';}if(host){let note=host.querySelector('[data-calculation-blocked]');if(!note){note=root.document.createElement('p');note.dataset.calculationBlocked='';note.setAttribute('role','status');host.prepend(note);}note.textContent=message();}return false;}
 function clear(host){host?.querySelectorAll('[data-calculation-blocked]').forEach(n=>n.remove());}
 const api={field,steps,pet,message,block,clear};root.KD_PROOF=api;if(typeof module==='object'&&module.exports)module.exports={...api,create:(proof,layout)=>{root.KD_PROVENANCE=proof;root.KD_PROOF_LAYOUT=layout;return api;}};
})(typeof window==='undefined'?{}:window);
