(function(root){
 'use strict';
 const COPY={
 ko:{title:'킹샷 데이터와 성장 도구',intro:'영웅·건물·연구 데이터를 확인하고 필요한 자원을 계산하세요. 비공식 KingShot 정보 사이트입니다.',search:'통합 검색',hint:'영웅 이름, 건물, 아이템 또는 공략을 검색하세요',tools:'성장 계산기',browse:'데이터 둘러보기',guides:'공략과 이벤트',empty:'검색 결과가 없습니다. 다른 이름이나 카테고리로 검색해 보세요.',count:'개 결과',open:'전체 보기',codes:'기프트코드',codeText:'게임 쿠폰과 공식 교환 방법을 확인하세요.',categories:{heroes:'영웅',buildings:'건물',research:'연구',gear:'장비',pets:'펫',masters:'거장',items:'아이템',events:'이벤트',guides:'가이드',tools:'계산기',data:'성장 데이터',codes:'기프트코드'}},
 en:{title:'Kingshot data & growth tools',intro:'Explore heroes, buildings and research. Calculate your next upgrade with this unofficial KingShot information hub.',search:'Search all content',hint:'Search heroes, buildings, items or guides',tools:'Upgrade calculators',browse:'Explore the data',guides:'Guides & events',empty:'No results. Try another name or category.',count:'results',open:'View all',codes:'Gift codes',codeText:'Find game gift codes and the official redemption guide.',categories:{heroes:'Heroes',buildings:'Buildings',research:'Research',gear:'Gear',pets:'Pets',masters:'Masters',items:'Items',events:'Events',guides:'Guides',tools:'Calculators',data:'Growth data',codes:'Gift codes'}},
 ja:{title:'Kingshot データと育成ツール',intro:'英雄・建物・研究データを確認し、次の育成に必要な素材を計算できる非公式情報サイトです。',search:'サイト内検索',hint:'英雄、建物、アイテム、ガイドを検索',tools:'育成計算機',browse:'データを探す',guides:'ガイドとイベント',empty:'一致する結果がありません。別の名前やカテゴリで検索してください。',count:'件',open:'すべて見る',codes:'ギフトコード',codeText:'ゲームのギフトコードと公式交換方法を確認できます。',categories:{heroes:'英雄',buildings:'建物',research:'研究',gear:'装備',pets:'ペット',masters:'巨匠',items:'アイテム',events:'イベント',guides:'ガイド',tools:'計算機',data:'育成データ',codes:'ギフトコード'}},
 'zh-tw':{title:'Kingshot 資料與成長工具',intro:'查看英雄、建築與研究資料，計算下一次升級所需材料。本網站為非官方資訊站。',search:'全站搜尋',hint:'搜尋英雄、建築、道具或攻略',tools:'成長計算器',browse:'探索資料',guides:'攻略與活動',empty:'找不到結果，請嘗試其他名稱或分類。',count:'筆結果',open:'查看全部',codes:'禮包碼',codeText:'查看遊戲禮包碼及官方兌換方式。',categories:{heroes:'英雄',buildings:'建築',research:'研究',gear:'裝備',pets:'寵物',masters:'巨匠',items:'道具',events:'活動',guides:'攻略',tools:'計算器',data:'成長資料',codes:'禮包碼'}}
 };
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function normalize(s){return String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' ').trim();}
 function search(entries,q){const terms=normalize(q).split(' ').filter(Boolean);if(!terms.length)return [];return entries.map(e=>{const title=normalize(e.title+' '+(e.aliases||[]).join(' '));const body=normalize(title+' '+e.description+' '+e.category);return {e,score:terms.every(t=>body.includes(t))?terms.reduce((n,t)=>n+(title.startsWith(t)?8:title.includes(t)?4:1),0):0};}).filter(r=>r.score).sort((a,b)=>b.score-a.score||a.e.title.localeCompare(b.e.title)).map(r=>r.e);}
 function lang(){const p=location.pathname.match(/^\/(en|ja|zh-tw)\//i);return p?p[1].toLowerCase():'ko';}
 const promises={};
 function catalog(l){return promises[l]||(promises[l]=fetch('/data/catalog/'+l+'.json?v=2026100606').then(r=>{if(!r.ok)throw Error('Search index unavailable');return r.json();}).catch(e=>{delete promises[l];throw e;}));}
 function card(e,labels){return '<a class="hub-card" href="'+esc(e.url)+'">'+(e.image?'<img src="'+esc(e.image)+'" alt="" width="64" height="64" loading="lazy" decoding="async">':'<span class="hub-mark" aria-hidden="true">↗</span>')+'<span><small>'+esc(labels.categories[e.category])+'</small><strong>'+esc(e.title)+'</strong><span>'+esc(e.description)+'</span></span></a>';}
 async function render(container){const l=lang(),c=COPY[l],prefix=l==='ko'?'':'/'+l;const entries=await catalog(l);if(!container.isConnected)return;
 const tools=entries.filter(e=>e.category==='tools'&&/\/calc-/.test(e.url));const groups=['heroes','buildings','research','gear','pets','masters','items','events'];
 container.innerHTML='<div class="professional-hub"><section class="hub-hero"><p class="hub-eyebrow">KINGSHOT DATA</p><h1>'+esc(c.title)+'</h1><p>'+esc(c.intro)+'</p><form class="hub-search" role="search"><label for="hub-search">'+esc(c.search)+'</label><input id="hub-search" type="search" autocomplete="off" placeholder="'+esc(c.hint)+'" aria-controls="hub-results"><p id="hub-search-status" role="status"></p></form><div id="hub-results" hidden></div></section><section class="hub-section"><div class="hub-section-title"><h2>'+esc(c.tools)+'</h2><a href="'+prefix+'/calculator/">'+esc(c.open)+' →</a></div><div class="hub-grid">'+tools.map(e=>card(e,c)).join('')+'</div></section><section class="hub-section"><h2>'+esc(c.browse)+'</h2><div class="hub-categories">'+groups.map(k=>{const group=entries.filter(e=>e.category===k);const e=(k==='gear'?group.find(e=>/governor-gear/.test(e.url)):null)||group.find(e=>/\/(heroes|buildings|research|pets?|masters|items|events)\/$/.test(e.url))||group[0];return e?'<a href="'+esc(e.url)+'"><strong>'+esc(c.categories[k])+'</strong><span>'+group.length+' '+esc(c.count)+'</span></a>':'';}).join('')+'</div></section><div id="hub-personal"></div><section class="hub-section hub-code"><div><p class="hub-eyebrow">GIFT CODES</p><h2>'+esc(c.codes)+'</h2><p>'+esc(c.codeText)+'</p></div><a class="hub-button" href="/'+l+'/guides/kingshot-giftcode.html">'+esc(c.open)+' →</a></section><section class="hub-section"><div class="hub-section-title"><h2>'+esc(c.guides)+'</h2><a href="/'+l+'/guides/">'+esc(c.open)+' →</a></div><div class="hub-grid">'+entries.filter(e=>e.category==='guides'&&/f2p-guide|bearhunt|transfer\.html/.test(e.url)).slice(0,3).map(e=>card(e,c)).join('')+'</div></section></div>';
 const input=container.querySelector('#hub-search'),results=container.querySelector('#hub-results'),status=container.querySelector('#hub-search-status');let timer;
 function update(){const q=input.value.trim();const hits=search(entries,q);results.hidden=!q;results.innerHTML=q?'<div class="hub-grid">'+hits.slice(0,18).map(e=>card(e,c)).join('')+'</div>':'';status.textContent=q?(hits.length?hits.length+' '+c.count:c.empty):'';clearTimeout(timer);if(q)timer=setTimeout(()=>root.KD_METRICS?.emit('search',{result_count:hits.length}),600);}
 input.addEventListener('input',update);input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('a')?.focus();}if(e.key==='Escape'){input.value='';update();}});container.querySelector('form').addEventListener('submit',e=>{e.preventDefault();results.querySelector('a')?.focus();});
 input.value=new URLSearchParams(location.search).get('q')||'';update();root.dispatchEvent(new CustomEvent('kd:page-ready'));return container;
 }
 const api={render,search,catalog,lang,COPY,esc,card};if(typeof module==='object'&&module.exports)module.exports={search,normalize};else root.KD_HUB=api;
})(typeof window!=='undefined'?window:this);
