'use strict';

const fs = require('fs');
const path = require('path');
const { mergeCouponData, normalizeCode } = require('./lib');

const ROOT = path.resolve(__dirname, '..', '..');
const COUPONS_FILE = path.join(ROOT, 'data', 'coupons.json');
const CANDIDATES_FILE = path.join(ROOT, 'data', 'coupon-candidates.json');
const CONFLICT_FILE = path.join(ROOT, 'DATA_CONFLICT_REPORT.md');
const writeMode = process.argv.includes('--write');

const sources = [
  require('./sources/official-centurygames'),
  require('./sources/kingshot-net'),
  require('./sources/kingshot-mastery'),
  require('./sources/kingshot-wiki')
];

function readJson(file, fallback) {
  if (!fs.existsSync(file)) return fallback;
  return JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
}

function stable(value) {
  return JSON.stringify(value, null, 2) + '\n';
}

function reportConflicts(conflicts) {
  const lines = [
    '# Coupon Data Conflict Report',
    '',
    'This file is generated by `scripts/coupons/update-coupons.js`.',
    'Conflicted codes are not promoted to the public active list unless an official source resolves the conflict.',
    ''
  ];
  if (!conflicts.length) {
    lines.push('No unresolved coupon source conflicts.');
  } else {
    for (const conflict of conflicts) {
      lines.push('## `' + conflict.code + '`', '');
      for (const source of conflict.sources) {
        lines.push('- ' + source.name + ': `' + source.observedStatus + '` (' + source.url + ')');
      }
      lines.push('');
    }
  }
  return lines.join('\n').trimEnd() + '\n';
}

function sourceSummary(source, status, count, error) {
  const result = { id: source.id, name: source.name, url: source.url, tier: source.tier, official: source.official, status, observations: count };
  if (error) result.error = error;
  return result;
}

function semanticRecord(record) {
  return JSON.stringify({
    code: record.code,
    status: record.status,
    until: record.until || null,
    expiresAt: record.expiresAt || null,
    notes: record.notes || null,
    officialVerified: Boolean(record.officialVerified),
    verifiedSourceCount: Number(record.verifiedSourceCount || 0),
    confidence: Number(record.confidence || 0),
    manualOverride: Boolean(record.manualOverride),
    sources: (record.sources || []).map(source => ({ id: source.id, observedStatus: source.observedStatus || null, observedExpiresAt: source.observedExpiresAt || null })).sort((a, b) => a.id.localeCompare(b.id))
  });
}

async function main() {
  const checkedAt = new Date().toISOString();
  const observations = [];
  const sourceRuns = [];

  for (const source of sources) {
    try {
      const found = await source.collect();
      observations.push(...found);
      sourceRuns.push(sourceSummary(source, 'ok', found.length));
      console.log('[coupon-source] ' + source.id + ': ' + found.length + ' observations');
    } catch (error) {
      sourceRuns.push(sourceSummary(source, 'error', 0, error.message));
      console.error('[coupon-source] ' + source.id + ': ' + error.message);
    }
  }

  const successful = sourceRuns.filter(item => item.status === 'ok');
  if (!successful.length) throw new Error('All coupon sources failed; existing data was not changed.');

  const currentData = readJson(COUPONS_FILE, { coupons: [] });
  const currentCandidates = readJson(CANDIDATES_FILE, { candidates: [] });
  const merged = mergeCouponData(currentData.coupons, currentCandidates.candidates, observations, checkedAt);
  const nextData = {
    schemaVersion: 2,
    lastCheckedAt: checkedAt,
    coupons: merged.coupons
  };
  const nextCandidates = {
    schemaVersion: 1,
    lastCheckedAt: checkedAt,
    candidates: merged.candidates
  };

  const oldPublished = new Map((currentData.coupons || []).map(item => [normalizeCode(item.code), item]));
  const changes = [];
  for (const record of merged.coupons) {
    const previous = oldPublished.get(record.normalizedCode);
    if (!previous) changes.push('published ' + record.code + ' as ' + record.status);
    else if (semanticRecord(previous) !== semanticRecord(record)) changes.push(record.code + ': metadata or status updated');
  }
  const oldCandidates = new Map((currentCandidates.candidates || []).map(item => [normalizeCode(item.code), item]));
  for (const record of merged.candidates) {
    const previous = oldCandidates.get(record.normalizedCode);
    if (!previous) changes.push('candidate ' + record.code);
    else if (semanticRecord(previous) !== semanticRecord(record)) changes.push(record.code + ': candidate evidence updated');
  }

  console.log('[coupon-update] sources checked: ' + sources.length);
  console.log('[coupon-update] sources successful: ' + successful.length);
  console.log('[coupon-update] observations: ' + observations.length);
  console.log('[coupon-update] published: ' + merged.coupons.length);
  console.log('[coupon-update] candidates: ' + merged.candidates.length);
  console.log('[coupon-update] conflicts: ' + merged.conflicts.length);
  console.log('[coupon-update] material changes: ' + changes.length);
  for (const change of changes) console.log('[coupon-change] ' + change);

  if (!writeMode) {
    console.log('[coupon-update] dry run; use --write to persist changes.');
    return;
  }

  if (!changes.length && fs.existsSync(CANDIDATES_FILE) && fs.existsSync(CONFLICT_FILE)) {
    console.log('[coupon-update] no material data change; files left untouched.');
    return;
  }

  fs.writeFileSync(COUPONS_FILE, stable(nextData), 'utf8');
  fs.writeFileSync(CANDIDATES_FILE, stable(nextCandidates), 'utf8');
  fs.writeFileSync(CONFLICT_FILE, reportConflicts(merged.conflicts), 'utf8');
}

main().catch(error => {
  console.error('[coupon-update] failed:', error.stack || error.message);
  process.exitCode = 1;
});
