'use strict';
const assert=require('node:assert/strict');
const {clean,safePath}=require('../js/my-progress');
const {deficit}=require('../js/calculator-workbench');
const {search}=require('../js/hub');
for(const bad of ['//outside.example','javascript:alert(1)','/../private','/x?redirect=https://outside.example','/x" onclick="bad'])assert.equal(safePath(bad),false);
assert.equal(safePath('/hero/gordon/'),true);
assert.equal(clean({version:1,recent:[{url:'//outside.example'}]}).recent.length,0);
assert.equal(clean({version:2,recent:[{url:'/heroes/'}]}).recent.length,0);
assert.equal(clean({version:1,recent:Array(40).fill({url:'/heroes/'})}).recent.length,20);
assert.equal(deficit(180,50),130);
assert.equal(deficit(180,200),0);
assert.equal(deficit(180,-1),null);
assert.equal(deficit(Infinity,0),null);
assert.equal(deficit(180,NaN),null);
const catalog=require('../data/catalog/ko.json');
assert(search(catalog,'Gordon').some(e=>e.url==='/hero/gordon/'));
assert(search(catalog,'고든').some(e=>e.url==='/hero/gordon/'));
assert.deepEqual(search(catalog,''),[]);
assert.deepEqual(search(catalog,'unlikely-no-matching-content-123456'),[]);
console.log('Hub search, storage validation and deficit regression tests passed.');
